language: julia

os:
  - linux

julia:
  - nightly
  # - 1.0.5
  - 1.5.0

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5.0
      os: linux
      script:
        - julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'